Repository HiQoNetIntership2019/HiQoDataGenerator, pull requests merged in 2019-07, with the labels that each got.

#87 refactored mapper extension
  HiQoDataGenerator.Core/Extensions/MapperExtension.cs
Labels: enhancement

#88 Added abstract logic in data generation
  HiQoDataGenerator.GeneratorCore/Exceptions/NegativeCountObjectsException.cs
  HiQoDataGenerator.GeneratorCore/HiQoDataGenerator.GeneratorCore.csproj
  HiQoDataGenerator.GeneratorCore/Interfaces/IDataGeneratorService.cs
  HiQoDataGenerator.GeneratorCore/Interfaces/IFieldsGenerator.cs
  HiQoDataGenerator.GeneratorCore/Models/Objects/GeneratedObject.cs
  HiQoDataGenerator.GeneratorCore/Models/Objects/GeneratedObjectsCollection.cs
  HiQoDataGenerator.GeneratorCore/Models/Prototypes/ConfigurablePrototype.cs
  HiQoDataGenerator.GeneratorCore/Models/Prototypes/ConstraintPrototype.cs
  HiQoDataGenerator.GeneratorCore/Models/Prototypes/FieldPrototype.cs
  HiQoDataGenerator.GeneratorCore/Services/DataGeneratorService.cs
  HiQoDataGenerator.Tests/HiQoDataGenerator.GeneratorCore/Services/DataGeneratorServiceTest.cs
  HiQoDataGenerator.Tests/HiQoDataGenerator.Tests.csproj
  HiQoDataGenerator.sln
Labels: enhancement, this is magic

#95 Enabled auto-migrations
  HiQoDataGenerator.Web/Startup.cs
Labels: enhancement

#96 add encoding seeds
  HiQoDataGenerator.DAL/Extensions/ModelBuilderExtension.cs
Labels: tiny issue

#99 added rabbitmq event bus
  HiQoDataGenerator.EventBus/ConnectionParams.cs
  HiQoDataGenerator.EventBus/EventBuses/InMemorySubscriptionManager.cs
  HiQoDataGenerator.EventBus/EventBuses/RabbitMqEventBus/DefaultRabbitMqPersistentConnection.cs
  HiQoDataGenerator.EventBus/EventBuses/RabbitMqEventBus/IRabbitMqPersistentConnection.cs
  HiQoDataGenerator.EventBus/EventBuses/RabbitMqEventBus/RabbitMqEventBus.cs
  HiQoDataGenerator.EventBus/Events/BusEvent.cs
  HiQoDataGenerator.EventBus/Handlers/IBusEventHandler.cs
  HiQoDataGenerator.EventBus/Helpers/SerializationHelper.cs
  HiQoDataGenerator.EventBus/HiQoDataGenerator.EventBus.csproj
  HiQoDataGenerator.EventBus/Interfaces/IEventBus.cs
  HiQoDataGenerator.EventBus/Interfaces/IEventBusSubscriptionsManager.cs
  HiQoDataGenerator.sln
Labels: epic changes, this is magic

#109 refactoring field values generator
  HiQoDataGenerator.GeneratorCore/Extensions/NumberConstants.cs
  HiQoDataGenerator.GeneratorCore/Extensions/RandomExtensions.cs
  HiQoDataGenerator.GeneratorCore/GeneratorCoreServices.cs
  HiQoDataGenerator.GeneratorCore/Generators/Base/BaseDateGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Base/BaseMinMaxGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Base/GeneratorBase.cs
  HiQoDataGenerator.GeneratorCore/Generators/FieldGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/BoolGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/ByteGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/ComplexGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/DateGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/DateTimeGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/DecimalGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/DoubleGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/GeneratorBase.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/IntegerGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/StringGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/RandomValuesGenerator.cs
  HiQoDataGenerator.GeneratorCore/Interfaces/IFieldValueGenerator.cs
  HiQoDataGenerator.GeneratorCore/Interfaces/IFieldsGenerator.cs
  HiQoDataGenerator.GeneratorCore/Interfaces/IRandomValuesGenerator.cs
  HiQoDataGenerator.GeneratorCore/Services/DataGeneratorService.cs
  HiQoDataGenerator.Tests/HiQoDataGenerator.GeneratorCore/Generators/Fields/IntegerGeneratorTest.cs
Labels: epic changes

#112 Denis scheduler subscriber
  HiQoDataGenerator.Core/Interfaces/IFileMetadataService.cs
  HiQoDataGenerator.Core/Interfaces/IFileStatusService.cs
  HiQoDataGenerator.Core/Interfaces/IGeneratedObjectFileSystemService.cs
  HiQoDataGenerator.Core/Services/FileMetadataService.cs
  HiQoDataGenerator.Core/Services/FileStatusService.cs
  HiQoDataGenerator.Core/Services/GeneratedObjectFileSystemService.cs
  HiQoDataGenerator.Core/Services/GeneratedObjectsService.cs
  HiQoDataGenerator.DAL/Contracts/Repositories/IFileStatusRepository.cs
  HiQoDataGenerator.DAL/Contracts/Repositories/IFilesGeneratedObjectsRepository.cs
  HiQoDataGenerator.DAL/Repositories/EntityFramework/FileStatusRepository.cs
  HiQoDataGenerator.Scheduler/Services/SchedulerHostedService.cs
  HiQoDataGenerator.SchedulerSubscriber/Extensions/SubscriberServices.cs
  HiQoDataGenerator.SchedulerSubscriber/Handlers/TimerEventHandler.cs
  HiQoDataGenerator.SchedulerSubscriber/HiQoDataGenerator.SchedulerSubscriber.csproj
  HiQoDataGenerator.SchedulerSubscriber/Program.cs
  HiQoDataGenerator.SchedulerSubscriber/Services/SubscriberHostedService.cs
  HiQoDataGenerator.SchedulerSubscriber/settings.json
  HiQoDataGenerator.sln
Labels: enhancement

#115 added generation from datasets and tests
  HiQoDataGenerator.Core/Interfaces/IDefinedDatasetService.cs
  HiQoDataGenerator.Core/Services/DefinedDatasetService.cs
  HiQoDataGenerator.DAL/Restrictions/SupportedTypes.cs
  HiQoDataGenerator.GeneratorCore/GeneratorCoreServices.cs
  HiQoDataGenerator.GeneratorCore/Generators/Base/GeneratorBase.cs
  HiQoDataGenerator.GeneratorCore/Generators/DatasetValueGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/FieldGenerator.cs
  HiQoDataGenerator.GeneratorCore/Interfaces/IDataGeneratorService.cs
  HiQoDataGenerator.GeneratorCore/Interfaces/IDatasetValueGenerator.cs
  HiQoDataGenerator.GeneratorCore/Interfaces/IFieldsGenerator.cs
  HiQoDataGenerator.GeneratorCore/Models/Prototypes/DatasetPrototype.cs
  HiQoDataGenerator.GeneratorCore/Models/Prototypes/FieldPrototype.cs
  HiQoDataGenerator.GeneratorCore/Services/DataGeneratorService.cs
  HiQoDataGenerator.Tests/HiQoDataGenerator.GeneratorCore/Services/DataGeneratorServiceTest.cs
  HiQoDataGenerator.Web/Controllers/DataGeneratorController.cs
  HiQoDataGenerator.Web/Extensions/MapperExtension.cs
  HiQoDataGenerator.Web/ViewModels/ConfigurableObjectViewModel.cs
Labels: enhancement

#119 enabled null dataset values in field models
  HiQoDataGenerator.Core/Entities/FieldModel.cs
  HiQoDataGenerator.Core/Extensions/MapperExtension.cs
  HiQoDataGenerator.DAL/DataContext.cs
  HiQoDataGenerator.DAL/Migrations/20190717131928_Add_DatasetFk.Designer.cs
  HiQoDataGenerator.DAL/Migrations/20190717131928_Add_DatasetFk.cs
  HiQoDataGenerator.DAL/Migrations/DataContextModelSnapshot.cs
  HiQoDataGenerator.DAL/Models/CustomObjectModels/Field.cs
  HiQoDataGenerator.Web/Controllers/DataGeneratorController.cs
  HiQoDataGenerator.Web/Extensions/MapperExtension.cs
  HiQoDataGenerator.Web/ModelsValidation/DatasetValidator.cs
  HiQoDataGenerator.Web/ViewModels/FieldViewModel.cs
Labels: bug police

#116 Refactoring generator
  HiQoDataGenerator.GeneratorCore/Extensions/EncodingTypes.cs
  HiQoDataGenerator.GeneratorCore/Extensions/StringConstants.cs
  HiQoDataGenerator.GeneratorCore/GeneratorCoreServices.cs
  HiQoDataGenerator.GeneratorCore/Generators/Base/BaseDateGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Base/BaseMinMaxGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Base/GeneratorBase.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/BoolGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/ByteGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/ComplexGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/DateTimeGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/DecimalGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/DoubleGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/GuidGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/IntegerGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/StringGenerator.cs
  HiQoDataGenerator.GeneratorCore/Generators/RandomValuesGenerator.cs
Labels: epic changes, this is magic

#118 fixed elmah logger
  HiQoDataGenerator.Infrastructure/LoggerExtensions/LoggerExtensions.cs
  HiQoDataGenerator.Web/LoggingInfrastructure/ElmahRedisClient.cs
  HiQoDataGenerator.Web/LoggingInfrastructure/RedisErrorLog.cs
Labels: tiny issue

#122 Added async saving generated objects
  HiQoDataGenerator.Core/Interfaces/IGeneratedObjectFileSystemService.cs
  HiQoDataGenerator.Core/Services/GeneratedObjectFileSystemService.cs
  HiQoDataGenerator.DAL/Repositories/FileSystem/FilesGeneratedObjectsRepository .cs
  HiQoDataGenerator.GeneratorCore/Generators/Fields/StringGenerator.cs
  HiQoDataGenerator.Web/Controllers/DataGeneratorController.cs
  HiQoDataGenerator.Web/Extensions/BackgroundDataSavingTasksQueue.cs
  HiQoDataGenerator.Web/Extensions/MapperExtension.cs
  HiQoDataGenerator.Web/HiQoDataGenerator.Web.csproj
  HiQoDataGenerator.Web/Interfaces/IBackgroundDataSavingTasksQueue.cs
  HiQoDataGenerator.Web/Services/QueuedDataSavingService.cs
  HiQoDataGenerator.Web/Startup.cs
  HiQoDataGenerator.Web/WebServices.cs
Labels: enhancement

#126 Fix cors
  HiQoDataGenerator.Web/Startup.cs
Labels: hotfix

#127 Added encoding data in bytes array
  HiQoDataGenerator.Web/Controllers/DataGeneratorController.cs
Labels: hotfix

#128 add Post method with id returned
  HiQoDataGenerator.Core/Interfaces/IDatasetService.cs
  HiQoDataGenerator.Core/Services/CustomDatasetService.cs
  HiQoDataGenerator.Core/Services/DatasetService.cs
  HiQoDataGenerator.Core/Services/DefinedDatasetService.cs
  HiQoDataGenerator.Web/Controllers/CustomDatasetsController.cs
Labels: enhancement

#140 Added generation many objects
  HiQoDataGenerator.Core/Interfaces/IGeneratedObjectFileSystemService.cs
  HiQoDataGenerator.Core/Services/GeneratedObjectFileSystemService.cs
  HiQoDataGenerator.Web/Controllers/DataGeneratorController.cs
Labels: tiny issue
